# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ccccf9cd0c1f81cc568df2cb59c387afa3b5254e968fc41c2b0dcc5db920bdd1c7570ee8e0c19cf713bddc1dc0c3099fc55d027b889370307ada48c4d9a0f1

test:
  secret_key_base: 46a129a158a7fedddf1cad21a2298fc83d05e986ad9f38b50655485575f1d3b332a2226abe91fcc1c0e970752909facb83be824da22f8029628159082f33b37e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
